<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.SyndicationFeed.ReaderWriter" Version="1.0.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.12" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Qbittorrent\Qbittorrent.csproj" />
    <ProjectReference Include="..\WeComCommon\WeComCommon.csproj" />
  </ItemGroup>
</Project>